### ISSUE TITLE
1.2 Tracks aren't shown in the track selector.

### ISSUE THREAD

**Issue by PandaPJYuri** [PabloMK7/CTGP7EFEPlugin#1]
All the tracks from the 1.2 update of CTGP-7 aren't included in the dropdown of the CTGP-7 tracks in the mission editor.
Furthermore, Bowser Castle is misspelt as Boweser Castle twice and SNES Ghost Valley 2 is listed as GBA Ghost Valley 2

**Comment by PabloMK7** [comment]
Fixed with cb60236
